Models/Asistencium.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Aplicacion.Models
{
    public partial class Asistencium
    {
        public int Id { get; set; }
        public int? IdAlumno { get; set; }     
        public int? IdCurso { get; set; }

        [Display(Name = "Fecha")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)] // Cambiar de DataType.DateTime a DataType.Date
        public DateTime? Fecha { get; set; }
        public bool? Estado { get; set; }

        [Display(Name = "Alumno")]
        public virtual Alumno? IdAlumnoNavigation { get; set; }

        [Display(Name = "Curso")]
        public virtual Curso? IdCursoNavigation { get; set; }
    }
}

Controllers/AsistenciumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Aplicacion.Models;
using Microsoft.AspNetCore.Authorization;

namespace Aplicacion.Controllers
{


    [Authorize]
    public class AsistenciumsController : Controller
    {
        private readonly DBPRUEBAContext _context;

        public AsistenciumsController(DBPRUEBAContext context)
        {
            _context = context;
        }

        // GET: Asistenciums
        public async Task<IActionResult> Index()
        {
            var cursos = await _context.Cursos
                .Include(c => c.HistoricoCursosAlumnos)
                .ThenInclude(x => x.IdAlumnoNavigation)
                .Include(a => a.Asistencia)
                .ToListAsync();
            return View(cursos);
        }

        // GET: Asistenciums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Asistencia == null)
            {
                return NotFound();
            }

            var asistencium = await _context.Asistencia
                .Include(a => a.IdAlumnoNavigation)
                .Include(a => a.IdCursoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asistencium == null)
            {
                return NotFound();
            }

            return View(asistencium);
        }

        // GET: Asistenciums/Create
        public IActionResult Create(int id)
        {
            List<Alumno> alumnos = new List<Alumno>();
            var historico = _context.HistoricoCursosAlumnos.Include(x => x.IdAlumnoNavigation).Where(x => x.IdCurso == id).ToList();
            return View(historico);
        }
        // GET: Asistenciums/GetAsistencia
        [HttpGet]
        public IActionResult GetAsistencia(int cursoId, DateTime fecha)
        {

            var response = new Response();
            var asistencia = _context.Asistencia
                .Where(a => a.IdCurso == cursoId && a.Fecha == fecha)
                .ToList();


            if(asistencia.Count > 0)
            {
                response.Estado = true;
            }
            else
            {
                response.Estado = false;
            }

            response.Data = asistencia;
            


            return Json(response);
        }


        // POST: Asistenciums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DateTime fecha, int cursoId, Dictionary<int, Asistencium> asistenciaList)
        {
            if (ModelState.IsValid)
            {
                List<Asistencium> asistencia = new List<Asistencium>();
                foreach (var entry in asistenciaList)
                {
                    asistencia.Add(new Asistencium
                    {
                        IdCurso = cursoId,
                        IdAlumno = entry.Value.IdAlumno,
                        Fecha = fecha,
                        Estado = entry.Value.Estado == true ? true : false,

                    });


                }

                foreach (var item in asistencia)
                {
                    var exist = await _context.Asistencia.Where(x => x.IdAlumno == item.IdAlumno && x.IdCurso == item.IdCurso && x.Fecha == item.Fecha).FirstOrDefaultAsync();
                    if (exist == null)
                    {
                        await _context.Asistencia.AddAsync(item);
                    }
                    else
                    {
                        exist.Estado = item.Estado;
                        _context.Update(exist);

                    }
                }




                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        // GET: Asistenciums/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Asistencia == null)
            {
                return NotFound();
            }

            var asistencium = await _context.Asistencia.FindAsync(id);
            if (asistencium == null)
            {
                return NotFound();
            }
            ViewData["IdAlumno"] = new SelectList(_context.Alumnos, "Id", "Id", asistencium.IdAlumno);
            ViewData["IdCurso"] = new SelectList(_context.Cursos, "Id", "Id", asistencium.IdCurso);
            return View(asistencium);
        }

        // POST: Asistenciums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdAlumno,IdCurso,Fecha,Estado")] Asistencium asistencium)
        {
            if (id != asistencium.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(asistencium);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AsistenciumExists(asistencium.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAlumno"] = new SelectList(_context.Alumnos, "Id", "Id", asistencium.IdAlumno);
            ViewData["IdCurso"] = new SelectList(_context.Cursos, "Id", "Id", asistencium.IdCurso);
            return View(asistencium);
        }

        // GET: Asistenciums/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Asistencia == null)
            {
                return NotFound();
            }

            var asistencium = await _context.Asistencia
                .Include(a => a.IdAlumnoNavigation)
                .Include(a => a.IdCursoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asistencium == null)
            {
                return NotFound();
            }

            return View(asistencium);
        }

        // POST: Asistenciums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Asistencia == null)
            {
                return Problem("Entity set 'DBPRUEBAContext.Asistencia'  is null.");
            }
            var asistencium = await _context.Asistencia.FindAsync(id);
            if (asistencium != null)
            {
                _context.Asistencia.Remove(asistencium);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AsistenciumExists(int id)
        {
            return (_context.Asistencia?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }

    public class Response
    {
        public bool Estado { get; set; }
        public object Data { get; set; }
    }
}

Views/Asistenciums/Create.cshtml
@model List<HistoricoCursosAlumno>

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Asistencium</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Alumnos</th>
                        <th scope="col">Registrar</th>
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.IdAlumnoNavigation.NombreCompleto</th>
                            <td>
                                <input type="checkbox" name="name" value="" />
                            </td>

                        </tr>
                    }
                   
                  
                </tbody>
            </table>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Asistenciums/Delete.cshtml
@model Aplicacion.Models.Asistencium

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Asistencia</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdAlumnoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdAlumnoNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCursoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCursoNavigation.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Asistenciums/Details.cshtml
@model Aplicacion.Models.Asistencium

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Asistencium</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdAlumnoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdAlumnoNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCursoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCursoNavigation.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Asistenciums/Edit.cshtml
@model Aplicacion.Models.Asistencium

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Asistencium</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IdAlumno" class="control-label"></label>
                <select asp-for="IdAlumno" class="form-control" asp-items="ViewBag.IdAlumno"></select>
                <span asp-validation-for="IdAlumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCurso" class="control-label"></label>
                <select asp-for="IdCurso" class="form-control" asp-items="ViewBag.IdCurso"></select>
                <span asp-validation-for="IdCurso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Asistenciums/Index.cshtml
@model IEnumerable<Aplicacion.Models.Curso>

@{
    ViewData["Title"] = "Index";
    List<Asistencium> asistenciaList = new List<Asistencium>();
}

<br />

<div class="text-center">
    <h2>Registro de Asistencia</h2>
</div>

<hr />


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>Asistencia</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>

                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary editar-btn"
                            data-bs-toggle="modal" data-bs-target="#exampleModal_@item.Id"
                            data-id="@item.Id">

                        <i class="bi bi-person-check"></i>
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Registro de asistencia</h5>
                                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form asp-action="Create" class="form">
                                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                        <input type="hidden" id="cursoId" name="cursoId" value="@item.Id" />

                                        <div class="form-group d-flex align-items-center">
                                            <input type="date"  id="fecha" class="form-control" name="fecha" placeholder="Seleccione una fecha" />
                                            @* <input type="button" class="form-control ml-2 btn btn-info btnCargar" value="Cargar @item.Id" data-cursoId="@item.Id"  /> *@ @* boton de buscar las asistencia por fecha *@
                                        </div>

                                        <table id="asistenciaTable" class="table">
                                            <thead>
                                                <tr>
                                                    <th scope="col">Alumnos</th>
                                                    <th scope="col">Registrar</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var alumno in item.HistoricoCursosAlumnos)
                                                {



                                                    <tr>
                                                        <th scope="row">@alumno.IdAlumnoNavigation.NombreCompleto</th>
                                                        <td>
                                                            <input type="hidden" name="asistenciaList[@alumno.IdAlumno].IdAlumno" value="@alumno.IdAlumno" />
                                                            <input type="checkbox" name="asistenciaList[@alumno.IdAlumno].Estado" value="true" />
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>

                                        <div class="modal-footer">
                                            <button type="submit" name="btnguardar" value="Guardar" class="btn btn-primary" />
                                            <i class="bi bi-check"></i>

                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> <i class="bi bi-x"></i> </button>

                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script>
        // $(document).ready(function () {
        //     // Controlador de eventos clic para todos los botones de clase .btnCargar
        //     $(document).on('click', '.btnCargar', function () {
        //         // Obtener el cursoId del atributo de datos
        //         var cursoId = $(this).closest('.modal').find('input[name="cursoId"]').val();
        //         var fecha = $(this).closest('.modal').find('input[name="fecha"]').val();

                //onchange en calendario
            $(document).ready(function () {
                $('#fecha').change(function () {
                    // Obtener el cursoId del campo de cursoId más cercano
                    var cursoId = $(this).closest('form').find('input[name="cursoId"]').val();
                    var fecha = $(this).val();

                // Realizar la solicitud AJAX
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetAsistencia", "Asistenciums")',
                    data: { cursoId: cursoId, fecha: fecha },
                    dataType: 'json',
                    success: function (data) {
                        console.log(data)
                        $.each(data.data, function (index, item) {
                           
                            var checkbox = $('input[name="asistenciaList[' + item.idAlumno + '].Estado"]');
                            checkbox.prop('checked', item.estado);
                        });
                        var btnGuardar = $('input[name="btnguardar"]');
                        btnGuardar.prop('disabled', data.estado);



                    }, error: function (xhr, status, error) {
                        console.error(xhr.responseText); // Imprimir el mensaje de error en la consola
                        alert('Se produjo un error al cargar la asistencia.'); // Mostrar una alerta al usuario
                    }
                });
            });

        });
    </script>
}


@* @section Scripts {
    <script>
        // Controlador de eventos clic para el botón #btnCargar
        $('#btnCargar' + $(this).data('cursoId')).click(function () {
            // Obtener el cursoId del atributo de datos
            var cursoId = $(this).data('cursoId');
            console.log(cursoId)
            var fecha = $('#fecha').val();

            // Realizar la solicitud AJAX
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetAsistencia", "Asistenciums")',
                data: { cursoId: cursoId, fecha: fecha },
                dataType: 'json',
                success: function (data) {
                    $.each(data, function (index, item) {
                        var checkbox = $('input[name="asistenciaList[' + item.IdAlumno + '].Estado"]');
                        checkbox.prop('checked', item.Estado);
                    });
                }, error: function (xhr, status, error) {
                    console.error(xhr.responseText); // Imprimir el mensaje de error en la consola
                    alert('Se produjo un error al cargar la asistencia.'); // Mostrar una alerta al usuario
                }
            });
        });

    </script> *@